-- EgliseCollecte: migration initiale. Exécuter avec Supabase CLI; ne jamais exposer service_role côté client.
create extension if not exists pgcrypto;
create schema if not exists church;
set search_path=church,public;
create type church.app_role as enum ('super_admin','admin','treasurer','collector','neighborhood_manager','auditor','member');
create type church.campaign_state as enum ('draft','active','suspended','closed','archived');
create type church.payment_state as enum ('pending','validated','void_requested','voided');
create type church.cash_state as enum ('open','submitted','validated','closed');
create table church.churches(id uuid primary key default gen_random_uuid(), name text not null, currency text not null default 'USD', created_at timestamptz not null default now());
create table church.profiles(id uuid primary key references auth.users(id) on delete restrict, church_id uuid references church.churches(id), full_name text not null, role church.app_role not null default 'collector', active boolean not null default true, created_at timestamptz not null default now());
create table church.neighborhoods(id uuid primary key default gen_random_uuid(), church_id uuid not null references church.churches(id), name text not null, commune text, unique(church_id,name));
create table church.church_groups(id uuid primary key default gen_random_uuid(), church_id uuid not null references church.churches(id), name text not null, unique(church_id,name));
create table church.members(id uuid primary key default gen_random_uuid(), church_id uuid not null references church.churches(id), member_no text not null, full_name text not null, sex text check(sex in ('M','F','other')), birth_date date, phone text, whatsapp text, address text, avenue text, neighborhood_id uuid references church.neighborhoods(id), group_id uuid references church.church_groups(id), status text not null default 'active' check(status in ('active','absent','transferred','deceased','suspended','archived')), photo_path text, notes text, created_by uuid references church.profiles(id), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(church_id,member_no));
create table church.campaigns(id uuid primary key default gen_random_uuid(), church_id uuid not null references church.churches(id), name text not null, description text, target_amount numeric(14,2) check(target_amount>=0), currency text not null default 'USD', starts_on date, due_on date, state church.campaign_state not null default 'draft', allow_overpayment boolean not null default false, created_by uuid references church.profiles(id), created_at timestamptz not null default now());
create table church.pledges(id uuid primary key default gen_random_uuid(), church_id uuid not null references church.churches(id), member_id uuid not null references church.members(id), campaign_id uuid not null references church.campaigns(id), amount numeric(14,2) not null check(amount>0), currency text not null default 'USD', due_on date, paid_amount numeric(14,2) not null default 0 check(paid_amount>=0), balance numeric(14,2) not null, status text not null default 'non_commence', note text, created_by uuid references church.profiles(id), created_at timestamptz not null default now(), unique(member_id,campaign_id));
create table church.cash_sessions(id uuid primary key default gen_random_uuid(), church_id uuid not null references church.churches(id), collector_id uuid not null references church.profiles(id), opened_at timestamptz not null default now(), closed_at timestamptz, state church.cash_state not null default 'open', declared_cash numeric(14,2), variance_note text, validated_by uuid references church.profiles(id));
create table church.payments(id uuid primary key default gen_random_uuid(), church_id uuid not null references church.churches(id), pledge_id uuid not null references church.pledges(id), collector_id uuid not null references church.profiles(id), cash_session_id uuid references church.cash_sessions(id), client_id uuid not null, amount numeric(14,2) not null check(amount>0), currency text not null, method text not null check(method in ('cash','mpesa','airtel_money','orange_money','bank','other')), transaction_ref text, note text, member_signature_path text, collector_signature_path text, proof_path text, receipt_no text not null, state church.payment_state not null default 'pending', occurred_at timestamptz not null default now(), validated_at timestamptz, validated_by uuid references church.profiles(id), void_reason text, voided_at timestamptz, voided_by uuid references church.profiles(id), created_at timestamptz not null default now(), unique(church_id,client_id), unique(church_id,receipt_no));
create table church.audit_logs(id bigint generated always as identity primary key, church_id uuid references church.churches(id), actor_id uuid references church.profiles(id), action text not null, entity text not null, entity_id uuid, old_data jsonb, new_data jsonb, metadata jsonb not null default '{}'::jsonb, occurred_at timestamptz not null default now());
alter table church.audit_logs enable row level security;
-- Privileged helper functions always derive identity from auth.uid().
create or replace function church.is_staff() returns boolean language sql stable security definer set search_path=church,public as $$select exists(select 1 from church.profiles where id=auth.uid() and active and role in ('super_admin','admin','treasurer','collector','neighborhood_manager','auditor'))$$;
create or replace function church.is_finance_admin() returns boolean language sql stable security definer set search_path=church,public as $$select exists(select 1 from church.profiles where id=auth.uid() and active and role in ('super_admin','admin','treasurer'))$$;
create or replace function church.refresh_pledge(p_id uuid) returns void language plpgsql security definer set search_path=church,public as $$declare v_paid numeric(14,2); begin select coalesce(sum(amount) filter(where state='validated'),0) into v_paid from church.payments where pledge_id=p_id; update church.pledges set paid_amount=v_paid,balance=greatest(amount-v_paid,0),status=case when v_paid=0 then 'non_commence' when v_paid>=amount then 'solde' when v_paid=amount/2 then 'a_moitie' when v_paid<amount/2 then 'paiement_faible' else 'paiement_avance' end where id=p_id; end $$;
create or replace function church.apply_payment_validation() returns trigger language plpgsql security definer set search_path=church,public as $$begin perform church.refresh_pledge(coalesce(new.pledge_id,old.pledge_id)); return coalesce(new,old); end $$;
create trigger payments_refresh_pledge after insert or update of state,amount or delete on church.payments for each row execute function church.apply_payment_validation();
create or replace function church.create_payment(p_pledge uuid,p_client_id uuid,p_amount numeric,p_currency text,p_method text,p_ref text default null,p_note text default null) returns uuid language plpgsql security definer set search_path=church,public as $$declare v_id uuid; v_church uuid; v_no text; begin if not church.is_staff() then raise exception 'unauthorized'; end if p_amount<=0 then raise exception 'amount must be positive'; end select church_id into v_church from church.pledges where id=p_pledge; if v_church is null then raise exception 'pledge not found'; end if exists(select 1 from church.payments where church_id=v_church and client_id=p_client_id) then select id into v_id from church.payments where church_id=v_church and client_id=p_client_id; return v_id; end if not exists(select 1 from church.pledges p join church.campaigns c on c.id=p.campaign_id where p.id=p_pledge and c.state='active') then raise exception 'campaign inactive'; end if p_amount>(select balance from church.pledges where id=p_pledge) and not (select c.allow_overpayment from church.pledges p join church.campaigns c on c.id=p.campaign_id where p.id=p_pledge) then raise exception 'overpayment not allowed'; end if (select role from church.profiles where id=auth.uid())='collector' and not exists(select 1 from church.cash_sessions where collector_id=auth.uid() and state='open') then raise exception 'open a cash session first'; end if v_no:='RCT-'||to_char(now(),'YYYY')||'-'||lpad(nextval('church.receipt_seq')::text,8,'0'); insert into church.payments(church_id,pledge_id,collector_id,cash_session_id,client_id,amount,currency,method,transaction_ref,note,receipt_no,state) values(v_church,p_pledge,auth.uid(),(select id from church.cash_sessions where collector_id=auth.uid() and state='open' order by opened_at desc limit 1),p_client_id,p_amount,p_currency,p_method,p_ref,p_note,v_no,'pending') returning id into v_id; insert into church.audit_logs(church_id,actor_id,action,entity,entity_id,new_data) values(v_church,auth.uid(),'CREATE_PAYMENT','payments',v_id,jsonb_build_object('amount',p_amount,'receipt',v_no)); return v_id; end $$;
create sequence church.receipt_seq;
-- Protect financial records: direct writes are denied; only RPC/function execution is permitted.
alter table church.churches enable row level security; alter table church.profiles enable row level security; alter table church.neighborhoods enable row level security; alter table church.church_groups enable row level security; alter table church.members enable row level security; alter table church.campaigns enable row level security; alter table church.pledges enable row level security; alter table church.payments enable row level security; alter table church.cash_sessions enable row level security;
create policy "staff read churches" on church.churches for select using(church.is_staff()); create policy "self profile" on church.profiles for select using(id=auth.uid() or church.is_finance_admin());
create policy "staff read neighborhoods" on church.neighborhoods for select using(church.is_staff()); create policy "staff read groups" on church.church_groups for select using(church.is_staff());
create policy "staff read members" on church.members for select using(church.is_staff()); create policy "staff read campaigns" on church.campaigns for select using(church.is_staff()); create policy "staff read pledges" on church.pledges for select using(church.is_staff());
create policy "payment visibility" on church.payments for select using(church.is_finance_admin() or collector_id=auth.uid()); create policy "cash visibility" on church.cash_sessions for select using(church.is_finance_admin() or collector_id=auth.uid()); create policy "audit finance read" on church.audit_logs for select using(church.is_finance_admin() or (actor_id=auth.uid() and (select role from church.profiles where id=auth.uid())='collector'));
revoke insert,update,delete on church.payments,church.pledges,church.audit_logs from anon,authenticated;
grant usage on schema church to authenticated; grant select on church.churches,church.profiles,church.neighborhoods,church.church_groups,church.members,church.campaigns,church.pledges,church.payments,church.cash_sessions,church.audit_logs to authenticated; grant execute on function church.create_payment(uuid,uuid,numeric,text,text,text,text) to authenticated;
create index members_search_idx on church.members(church_id,full_name); create index payments_pledge_idx on church.payments(pledge_id,state); create index pledges_campaign_idx on church.pledges(campaign_id,status);
